import type { Song } from '@/lib/types';

export const mockSongs: Song[] = [
  {
    id: '1',
    title: 'Cosmic Drift',
    artist: 'Galaxy Runners',
    album: 'Starlight Echoes',
    duration: '3:45',
    coverArt: 'https://placehold.co/300x300/9D7CBF/2B2836.png',
  },
  {
    id: '2',
    title: 'Nebula Flow',
    artist: 'Galaxy Runners',
    album: 'Starlight Echoes',
    duration: '4:12',
    coverArt: 'https://placehold.co/300x300/9D7CBF/2B2836.png',
  },
  {
    id: '3',
    title: 'Pulsar Wave',
    artist: 'Galaxy Runners',
    album: 'Starlight Echoes',
    duration: '2:58',
    coverArt: 'https://placehold.co/300x300/9D7CBF/2B2836.png',
  },
  {
    id: '4',
    title: 'Oceanic Pulse',
    artist: 'Tidal Waves',
    album: 'Deep Blue',
    duration: '5:02',
    coverArt: 'https://placehold.co/300x300/7CB3BF/2B2836.png',
  },
  {
    id: '5',
    title: 'Coral Dreams',
    artist: 'Tidal Waves',
    album: 'Deep Blue',
    duration: '3:33',
    coverArt: 'https://placehold.co/300x300/7CB3BF/2B2836.png',
  },
  {
    id: '6',
    title: 'Sunrise on the City',
    artist: 'Urban Glow',
    album: 'Metropolis Heartbeat',
    duration: '4:20',
    coverArt: 'https://placehold.co/300x300/BF9D7C/2B2836.png',
  },
  {
    id: '7',
    title: 'Midnight Drive',
    artist: 'Urban Glow',
    album: 'Metropolis Heartbeat',
    duration: '3:55',
    coverArt: 'https://placehold.co/300x300/BF9D7C/2B2836.png',
  },
  {
    id: '8',
    title: 'Neon Reflections',
    artist: 'Urban Glow',
    album: 'Metropolis Heartbeat',
    duration: '4:01',
    coverArt: 'https://placehold.co/300x300/BF9D7C/2B2836.png',
  },
  {
    id: '9',
    title: 'Whispering Woods',
    artist: 'Forest Dwellers',
    album: 'Ancient Roots',
    duration: '6:15',
    coverArt: 'https://placehold.co/300x300/7CBF8E/2B2836.png',
  },
  {
    id: '10',
    title: 'River of Time',
    artist: 'Forest Dwellers',
    album: 'Ancient Roots',
    duration: '5:30',
    coverArt: 'https://placehold.co/300x300/7CBF8E/2B2836.png',
  },
  {
    id: '11',
    title: 'First Light',
    artist: 'Tidal Waves',
    album: 'Morning Mist',
    duration: '3:50',
    coverArt: 'https://placehold.co/300x300/7CBFBF/2B2836.png',
  },
   {
    id: '12',
    title: 'Quantum Leap',
    artist: 'Galaxy Runners',
    album: 'Event Horizon',
    duration: '4:44',
    coverArt: 'https://placehold.co/300x300/BF7CBF/2B2836.png',
  },
   {
    id: '13',
    title: 'Lonely Skyscraper',
    artist: 'Urban Glow',
    album: 'Concrete Jungle',
    duration: '3:10',
    coverArt: 'https://placehold.co/300x300/BFA27C/2B2836.png',
  },
   {
    id: '14',
    title: 'Mossy Stones',
    artist: 'Forest Dwellers',
    album: 'Ancient Roots',
    duration: '4:05',
    coverArt: 'https://placehold.co/300x300/7CBF8E/2B2836.png',
  },
  {
    id: '15',
    title: 'Lunar Tides',
    artist: 'Tidal Waves',
    album: 'Deep Blue',
    duration: '4:18',
    coverArt: 'https://placehold.co/300x300/7CB3BF/2B2836.png',
  },
];
